apiVersion: v1
kind: Namespace
metadata:
  name: proxy-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-proxy
  namespace: proxy-server
  labels:
    app: proxy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-server
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
      - name: proxy-http
        image: msr2.konitzer.dev/wkonitzer/proxy-server:latest  # Replace with your actual image
        ports:
        - containerPort: 8080
        env:
        - name: MODE
          value: "http"
      - name: proxy-https
        image: msr2.konitzer.dev/wkonitzer/proxy-server:latest
        ports:
        - containerPort: 8443
        env:
        - name: MODE
          value: "https"
        volumeMounts:
        - name: cert-volume
          mountPath: /app
      volumes:
      - name: cert-volume
        secret:
          secretName: proxy-server-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: proxy-server
  name: proxy-service
spec:
  type: LoadBalancer
  selector:
    app: proxy-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
